name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build with make
      run: make" | Out-File -FilePath .github/workflows/build.yml -Encoding utf8
